import express from "express";
import userRoutes from "./user.routes";
import zoneRoutes from "./zone.routes";
import categoryRoutes from "./category.routes";
import formRoutes from "./forms.routes";
import marketplacelistingRoutes from "./marketplaceListings.routes";
import routAService from "./rentAService.routes";
import fieldRoutes from "./field.routes";
import dropdownRoutes from "./dropdown.routes";
import paymentRoutes from "./payment.routes";
import bookingRoutes from "./booking.routes";
import damageReportRoutes from "./damageReport.routes";
import BusinessSetting from "./businessSetting.routes";
import employeeManagementRoutes from "./employeeManagement.routes";
import refundRoutes from "./refundManagement.routes";
import reviewRoutes from "./review.routes";
import faqRoutes from "./faq.routes";
import employeeRoleRoutes from "./employeeRole.routes";
import helpSupportRoutes from "./helpSupport.routes";
import contactUsRoutes from "./contactUs.routes";
import chatRoutes from "./chat.routes";
import favouritesRoutes from "./favourites.route";
import analyticsRoutes from "./analytics.routes";
import refundPoliciesRoutes from "./refundPolicies.routes";
import refundRequestsRoutes from "./refundRequests.routes";

const router = express.Router();

router.use("/users", userRoutes);
router.use("/chats", chatRoutes);
router.use("/payments", paymentRoutes);
router.use("/zones", zoneRoutes);
router.use("/categories", categoryRoutes);
router.use("/forms", formRoutes);
router.use("/marketplace-listings", marketplacelistingRoutes);
router.use("/rent-service", routAService);
router.use("/fields", fieldRoutes);
router.use("/dropdowns", dropdownRoutes);
router.use("/bookings", bookingRoutes);
router.use("/tickets", damageReportRoutes);
router.use("/businessSetting", BusinessSetting);
router.use("/employee-management", employeeManagementRoutes);
router.use("/refunds", refundRoutes);
router.use("/refund-policies", refundPoliciesRoutes);
router.use("/refund-requests", refundRequestsRoutes);
router.use("/reviews", reviewRoutes);
router.use("/faqs", faqRoutes);
router.use("/employee-roles", employeeRoleRoutes);
router.use("/queries", helpSupportRoutes);
router.use("/contact-us", contactUsRoutes);
router.use("/chat", chatRoutes);
router.use("/favourites", favouritesRoutes);
router.use("/analytics", analyticsRoutes);

export default router;
