export const endpointAccessMap: Record<string, string> = {
  "/zones": "zone",
  "/categories": "category",
  "/fields": "field",
  // "/users": "users",
  "/dashboard": "dashboard",
  "/marketplace-listings": "listing",
  "/businessSetting": "business",
  "/tickets": "tickets",
  "/refunds": "refund",
  "/employee-management": "employee",
  "/analytics": "analytics",
  "/messages": "messages",
  "/queries": "support",
  "/faqs": "faqs",
  "/employee-roles": "employee",
  "/contact-us": "support",
  "/favourites": "listing",
  "/reviews": "reports",
  "/refund-policies": "rental-policies",
  "/refund-requests": "refund",
  "/payments": "payment-methods",
  "/sms": "sms",
  "/mail": "mail",
  "/map": "map",
  "/socials": "socials",
  "/recaptcha": "recaptcha",
  "/firebase": "firebase",
};
